version: '3.8'
services:
  api:
    build: ./api
    environment:
      - MONGO_URL=${MONGO_URL}
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - app-network
  src:
    build: ./src
    ports:
      - "8001:8001"
    environment:
      - MONGO_URL=${MONGO_URL}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
