version: '3.8'
services:
  api:
    build: ./api
    environment:
      - MONGO_URL=${MONGO_URL}
      - NODE_ENV=${NODE_ENV}
    ports:
      - "8100:8100"
    networks:
      - app-network
  src:
    build: ./src
    ports:
      - "8101:8101"
    environment:
      - MONGO_URL=${MONGO_URL}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
